### ISSUE TITLE
Send Message continent

### ISSUE THREAD

**Issue by bryantson** [githubuniverseworkshops/GitHub-Actions-Planet-GitHubUniverse2021#5]
# Welcome to Send Message continent

![5_SendMessage](https://user-images.githubusercontent.com/5396174/138540839-defaf1b4-e5d7-4ce1-832b-44ed4b76b4ee.jpg)

> Before crossing the long ocean, we need to send messages to our friends and families that we are alive and okay

## Your mission

- [x] Learn about different GitHub Actions plugins to send messages
- [x] Activity - Send messages through Microsoft Teams and Slack

# Learn about different GitHub Actions plugins to send messages

You can find different **GitHub Actions** plugin to send messages or to notify users in **GitHub Actions Marketplace**

![image](https://user-images.githubusercontent.com/5396174/138631391-d10c3682-8228-425e-81b9-f120f121f004.png)

For example, you can send a Slack message through Slack by just including `slackapi/slack-github-action` GitHub Actions plugin.

```yaml
- name: Post to a Slack channel
  id: slack
  uses: slackapi/slack-github-action@v1.14.0
  with:
    channel-id: 'CHANNEL_ID'  # Slack channel id to post message
    slack-message: 'posting from a github action!'
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

And there is even a way to send a text message through **Twilio**!

```yaml
- name: 'Sending SMS Notification'
  uses: twilio-labs/actions-sms@v1
  with:
    fromPhoneNumber: '+1(234)5678901'
    toPhoneNumber: '+1(234)3334444'
    message: 'Hello from Twilio'
  env:
    TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
    TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
    TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
```

## Activity - Send messages through Microsoft Teams and Slack

We will send our greeting messages from GitHub Actions planet through Slack and Microsoft Teams. To do so, we can utilize these different GitHub Actions pipeline script under `.github/workflows`:

- `action-send-slack-msg.yml`: We can use this GitHub Actions pipeline script to send a Slack message. Slack App is already setup with required **Bot Token** permission with `chat:write` permission
- `action-send-team-msg.yml`: We can use this GitHub Actions pipeline script to send a Microsoft Teams message. All we need is a Webhook link!

## ⏭️  After you are done, you can close this issue to move forward to next one.
